# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de12c562350152757bf4e225ff25c8fe8b0810078e451b31dbc5a4758d12f0cfeed45604057ff61a911b523669bffbcab512bc80d7733dd7b30c4683e8313fc3

test:
  secret_key_base: a43ee31b184f49e1384fab0e174a30e1708b00fd40b99b935f1dd273c78043afba330705af3df41a841022f578e24e262adeafbf4b590f7ce0ec3e2085c44d6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
